version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - rails-network
  
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./create-db-user.sql:/docker-entrypoint-initdb.d/create-db-user.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - rails-network
  
  adminer:
    image: adminer
    depends_on:
      - db
    environment:
      - DB_HOST=db
    ports:
      - "8080:8080"
    networks:
      - rails-network

volumes:
  postgres-data:

networks:
  rails-network:
    driver: bridge